translator:
  provider:
#    proxy:
#      host: proxy-host
#      port: proxy-port
    maxsize: 4000
  glossary:
    path: glossaries.txt
  blacklist:
    equal:
    contain:
  file:
    overwrite: false
